import * as dotenv from "dotenv";
dotenv.config();

const SUPABASE_URL = process.env.SUPABASE_URL as string;
console.log("SUPABASE_URL", SUPABASE_URL);
const SUPABASE_SERVICE_ROLE_KEY = process.env
  .SUPABASE_SERVICE_ROLE_KEY as string;
console.log("SUPABASE_SERVICE_ROLE_KEY", SUPABASE_SERVICE_ROLE_KEY);
const SUPABASE_ACCESS_TOKEN = process.env.SUPABASE_ACCESS_TOKEN as string;
console.log("SUPABASE_ACCESS_TOKEN", SUPABASE_ACCESS_TOKEN);
const SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID = process.env
  .SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID as string;
console.log("SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID", SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID);
const SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET = process.env
  .SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET as string;
console.log("SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET", SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET);
const SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI = process.env
  .SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI as string;
console.log("SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI", SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI);

if (!SUPABASE_ACCESS_TOKEN) throw new Error("Missing SUPABASE_ACCESS_TOKEN");
if (!SUPABASE_URL) throw new Error("Missing SUPABASE_URL");
if (!SUPABASE_SERVICE_ROLE_KEY)
  throw new Error("Missing SUPABASE_SERVICE_ROLE_KEY");

export {
  SUPABASE_ACCESS_TOKEN,
  SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID,
  SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET,
  SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI,
  SUPABASE_SERVICE_ROLE_KEY,
  SUPABASE_URL,
};
